# Generated by Django 4.1 on 2023-12-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('userpass', models.CharField(max_length=128, unique=True)),
                ('useremail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
