# Generated by Django 4.1 on 2023-12-27 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 13, 23, 58, 138106, tzinfo=datetime.timezone.utc)),
        ),
    ]
