# Generated by Django 5.0.1 on 2024-01-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_remove_person_name_person_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='name',
        ),
    ]
