# Generated by Django 4.1 on 2023-12-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=264, unique=True)),
                ('lname', models.CharField(max_length=264, unique=True)),
                ('email', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
